Test/keyvault
nearform/fastify-secrets-azure pull request #109
Opened 2021-07-21 13:35 UTC by miguelarias-nf

adding keyvault creation and delete to the gh action

2021-07-21 13:51 UTC, simoneb requested changes

2021-07-21 13:51 UTC, simoneb commented on .github/workflows/ci.yml
> +# Commenting out to add workflow dispatch
remove

2021-07-21 13:51 UTC, simoneb commented on .github/workflows/ci.yml
> +          echo "LOCATION=westeurope" >> $GITHUB_ENV
Let's use global env vars instead. See [docs](https://docs.github.com/en/actions/reference/environment-variables):

>To set custom environment variables, you need to specify the variables in the workflow file. You can define environment variables for a step, job, or entire workflow

2021-07-21 13:51 UTC, simoneb commented on .github/workflows/ci.yml
> +          echo "LOCATION=westeurope" >> $GITHUB_ENV
also, let's not use date, let's use e.g. GITHUB_RUN_ID (built-in env var). Also, let's not use it repeatedly, let's create a global env var which contains the vault name and use it everywhere

2021-07-21 13:51 UTC, simoneb commented on .github/workflows/ci.yml
> +          azcliversion: 2.0.72
remove version, let's use latest

2021-07-21 13:51 UTC, simoneb commented on .github/workflows/ci.yml
> +          github-token: ${{ secrets.GITHUB_TOKEN }}
keep a new line at the end of the file

2021-07-21 13:51 UTC, simoneb commented on .github/workflows/ci.yml
> +            az keyvault create --location ${{ env.LOCATION }} --name ${{ env.AZURE_KV_NAME }}-${{ env.NDATE }} --resource-group ${{ secrets.KEYVAULT_RESOURCE_GROUP }} --enable-soft-delete true
here and everywhere, why don't we use global env vars to configure the az CLI instead of repeating the same arguments like location over and over? see https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration#cli-configuration-values-and-environment-variables

2021-07-21 13:51 UTC, simoneb commented on .github/workflows/ci.yml
> -          AZURE_VAULT_NAME: ${{ secrets.AZURE_VAULT_NAME }}
once this is merged, let's remember to remove the AZURE_VAULT_NAME secret as it will be unused then

2021-07-21 15:38 UTC, simoneb commented on .github/workflows/ci.yml
> +            #--no-wait
remove unnecessary comments

2021-07-21 15:38 UTC, simoneb commented on .github/workflows/ci.yml
> +          echo "LOCATION=westeurope" >> $GITHUB_ENV
this is unnecessary complex. just populate global env vars!

2021-07-21 15:38 UTC, simoneb commented on .github/workflows/ci.yml
> +          azcliversion: latest
remove, it will default to latest

2021-07-21 15:38 UTC, simoneb commented on .github/workflows/ci.yml
> +            az keyvault set-policy -n ${{ env.AZURE_KV_NAME }} --resource-group ${{ secrets.KEYVAULT_RESOURCE_GROUP }} --certificate-permissions backup create delete deleteissuers get getissuers impo
instead of providing the resource group every single time to the command, you can simply populate a global environment variable that the az CLI will use automatically

2021-07-21 15:38 UTC, simoneb commented on .github/workflows/ci.yml
> +          azcliversion: latest
remove

2021-07-21 17:57 UTC, miguelarias-nf commented
All request have been implemented

2021-07-22 08:32 UTC, simoneb approved these changes

2021-07-22 08:49 UTC, simoneb approved these changes

2021-07-22 08:50 UTC, merged